# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RPGAsyncDrawCellDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RPGAsyncDrawCellDemo
pod 'YYKit'
pod 'GDPerformanceView'
  target 'RPGAsyncDrawCellDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RPGAsyncDrawCellDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
